#!/bin/bash
# CLI Workflow Examples for Arrangent
# Demonstrates common workflows using the CLI

echo "=== Arrangent CLI Workflow Examples ==="
echo ""

# Workflow 1: Basic Task Execution
echo "### Workflow 1: Basic Task Execution ###"
echo ""
echo "Step 1: Start the server"
echo "  $ yarn arrangent server"
echo ""
echo "Step 2: Submit a topology configuration"
echo "  $ yarn arrangent submit topologies/sample.yaml"
echo ""
echo "Step 3: Monitor execution in real-time"
echo "  $ yarn arrangent monitor"
echo ""
echo "Expected output:"
echo "  [14:30:01] splitter-a1b2 🔵 RUNNING"
echo "  [14:30:03] splitter-a1b2 🟢 COMPLETED"
echo "  [14:30:04] worker-c3d4 🔵 RUNNING (3 instances)"
echo "  ..."
echo ""
echo "---"
echo ""

# Workflow 2: Human-in-the-Loop Intervention
echo "### Workflow 2: Human-in-the-Loop Intervention ###"
echo ""
echo "Step 1: Monitor shows agent waiting for input"
echo "  [14:32:47] worker-xyz 🟡 WAITING FOR INPUT:"
echo "     Please clarify requirement X"
echo ""
echo "Step 2: Inspect the instance"
echo "  $ yarn arrangent inspect worker-xyz"
echo ""
echo "Step 3: Provide guidance to the agent"
echo "  $ yarn arrangent interact worker-xyz"
echo "  > 'Requirement X means focus on performance optimization'"
echo ""
echo "Step 4: Agent continues with new context"
echo "  [14:32:50] worker-xyz 🔵 RUNNING"
echo "  [14:32:52] worker-xyz 🟢 COMPLETED"
echo ""
echo "---"
echo ""

# Workflow 3: Debugging Agent Issues
echo "### Workflow 3: Debugging Agent Issues ###"
echo ""
echo "Step 1: List all instances to find problematic ones"
echo "  $ yarn arrangent list"
echo ""
echo "Step 2: Inspect detailed state"
echo "  $ yarn arrangent inspect node-id"
echo ""
echo "Step 3: View execution history"
echo "  $ yarn arrangent logs instance-id"
echo ""
echo "Step 4: Restart if needed"
echo "  $ yarn arrangent restart instance-id"
echo ""
echo "---"
echo ""

# Workflow 4: Pausing and Resuming
echo "### Workflow 4: Pausing and Resuming Execution ###"
echo ""
echo "Step 1: Use CLI to pause an instance"
echo "  $ curl -X PUT http://localhost:3000/api/v1/instances/{id}/status \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"action\": \"pause\"}'"
echo ""
echo "Step 2: Review the state while paused"
echo "  $ yarn arrangent inspect instance-id"
echo ""
echo "Step 3: Resume when ready"
echo "  $ curl -X PUT http://localhost:3000/api/v1/instances/{id}/status \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"action\": \"resume\"}'"
echo ""
echo "---"
echo ""

# Workflow 5: Visualizing Topology
echo "### Workflow 5: Visualizing Topology ###"
echo ""
echo "Step 1: View topology structure"
echo "  $ yarn arrangent topology"
echo ""
echo "Expected output:"
echo "  Topology: Sample Workflow"
echo "  Level 0:"
echo "    - task-splitter"
echo "  Level 1:"
echo "    - parallel-workers (3 instances)"
echo "  Level 2:"
echo "    - result-merger"
echo ""
echo "---"
echo ""

# Workflow 6: Using HTTP API Directly
echo "### Workflow 6: Using HTTP API for Custom Integration ###"
echo ""
echo "Step 1: Discover available APIs"
echo "  $ curl http://localhost:3000/api/v1"
echo ""
echo "Step 2: Create a topology programmatically"
echo "  $ curl -X POST http://localhost:3000/api/v1/topologies \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d @topology.json"
echo ""
echo "Step 3: Start execution"
echo "  $ curl -X POST http://localhost:3000/api/v1/executions \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"input\": {...}}'"
echo ""
echo "Step 4: Watch progress via WebSocket"
echo "  # Connect WebSocket client to ws://localhost:3000"
echo "  # Receive real-time updates"
echo ""
echo "---"
echo ""

# Workflow 7: Running Demo Cases
echo "### Workflow 7: Running Demo Cases ###"
echo ""
echo "Simple flow demo:"
echo "  $ yarn demo"
echo ""
echo "Documentation analysis demo:"
echo "  $ yarn demo:doc"
echo ""
echo "Code review demo:"
echo "  $ yarn demo:review"
echo ""
echo "Video blogger case study:"
echo "  $ yarn case:blogger"
echo ""
echo "---"
echo ""

echo "=== Workflows Complete ==="
echo ""
echo "For more detailed information:"
echo "  - See CLI_GUIDE.md for complete command reference"
echo "  - See README.md for architecture and design philosophy"
echo "  - See examples/http-api-examples.sh for HTTP API usage"
